# Pustka
Tym razem zaczynacie z pustym notebookiem. To trochę symulacja sytuacji przeprowadzania projektu. Dzisiaj przerobimy przede wszystkim:
* organizacja kodu z poprzednich zajęć - tworzymy funkcję która wczytuje dane i robi tfr
* pętla przez osoby badane - robimy tfr dla wszystkich osób
* uśrednianie tfr - aby otrzymać między innymi średnie wykresy tfr
* selekcja regionów zainteresowania
* analiza

Ostatni punkt, wraz z wielokrotnymi porównaniami omówimy jeszcze w przyszłym tygodniu. To będzie ostatnia cegła do twierdzy waszych kompetencji przed Wami pozostanie tylko zabawa z projektem.

## Zadanie 01
Stwórz w tym notebook'u najpierw dwie komórki:
* w pierwszej umieść wszystkie potrzebne importy
* w drugiej zaś kod, którym wczytasz jeden plik oraz utworzysz dla niego tfr
Potrzebny kod znajdziesz w notebook'u z ostatnich zajęć. Spróbuj wybrać to co potrzebne oraz zrobić kosmetyczną zmianę tak aby kod robił tfr dla obu warunków razem. To ważne - druga komórka ma robić tfr bez podziału na warunki - dla obu warunków łącznie!

## Zadanie 02
Przekształć teraz kod z drugiej komórki w funkcję, która przyjmuje nazwę pliku oraz zwraca tfr dla tego pliku.
Przypominam, że funkcje piszemy tak:
```python
def nazwa_funkcji(argument1, argument2):
    # cośtam cośtam
    # cośtam cośtam
    return jakiś_wynik
```
w Waszym wypadku 'sygnatura' funkcji będzie taka:
```python
def daj_mnie_ten_tfr(nazwa_pliku):
    # wczytanie pliku
    # definicja zmiennych do analizy tfr
    # analiza tfr
    return tfr
```

## Zadanie 03
Wreszcie gdy mamy już interesującą nas funkcję, spróbujemy wykonać ją dla wszystkich plików. Ale dojdziemy do tego krok po kroku.
### Krok 1
Wyobraźmy sobie, że mamy listę plików o nazwie `files` jak napisać pętlę aby robiła coś kolejno z nazwami plików?  
Na przykładzie funkcji print:

In [1]:
files = ['plik1.fif', 'plik2.fif', 'jakiś dziwny plik.png',
         'Jak python zmienił moje życie - wypracowanie.docx']

In [2]:
for this_file in files:
    print(this_file)

plik1.fif
plik2.fif
jakiś dziwny plik.png
Jak python zmienił moje życie - wyprawcowanie.docx


In [3]:
for this_file in files:
    print(this_file[::2])

pi1ff
pi2ff
jkśdin lkpg
Jkpto mei oeżce-wpacwnedc


W waszym wypadku wystarczy podmienić funkcję `print` na Waszą funkcję do wczytywania pliku i robienia tfr.  

### Krok 2
Pozostaje jeszcze jedna sprawa - chcielibyśmy jakoś agregować te tfr-y na przykład zbierać do jednej listy.  
Całe szczęście nie jest to trudne. Poniżej konkretny przykład, weźmy najpierw funkcję, która zwraca nam trzy
losowe liczby:

In [4]:
import numpy as np

def three_random():
    return np.random.rand(3)

In [5]:
three_random()

array([0.33270893, 0.61921339, 0.85700122])

In [6]:
three_random()

array([0.77534818, 0.67226044, 0.33410465])

Za każdym razem wektor trzech losowych liczb między zero a jeden. Teraz chcemy wykonać tę funkcję pięć razy i każdy z pięciu kolejnych wyników przechowywać w liście `liczby`.

In [7]:
# tworzymy pustą listę:
liczby = list()

# pięć razy ...
for i in range(5):
    # uruchamiany naszą funkcję:
    trzy = three_random()
    
    # a następnie doklejamy jej wynik do listy 'liczby':
    liczby.append(trzy)

In [8]:
liczby

[array([0.50266703, 0.33421762, 0.59706877]),
 array([0.68342066, 0.33242564, 0.49359561]),
 array([0.76438025, 0.9343985 , 0.22734359]),
 array([0.49356043, 0.12667151, 0.421795  ]),
 array([0.10468988, 0.81883416, 0.01626112])]

In [10]:
liczby[-2:]

[array([0.49356043, 0.12667151, 0.421795  ]),
 array([0.10468988, 0.81883416, 0.01626112])]

W ten sam sposób chcecie wykonywać na kolejnych plikach waszą funkcję do tfr-ów a następnie doklejać je do listy.

### Krok 3
Twoja kolej, czas przeanalizować te dane! Uzupełnij kod poniżej:

In [ ]:
tfrs = list()
for ___ in ___:
    ___ = daj_mnie_ten_tfr(fname)
    ____.append(tfr)

Tak, tylko tyle wystarczy aby przejść z poziomu pojedynczego pliku, na przetwarzanie wielu!
W tym punkcie, jeżeli masz listę tfr'ów, możesz skorzystać z wygodnej funkcji mne python'a do uśredniania wielu tfr'ów.  
Ale, ojej, zapomnieliśmy o jednej rzeczy! Chcielibyśmy aby każdy tfr był baseline-corrected. Całe szczęście każdy tfr ma metodę [`apply_baseline`](https://martinos.org/mne/stable/generated/mne.time_frequency.AverageTFR.html#mne.time_frequency.AverageTFR.apply_baseline) (tak, to poprzednie to link do dokumentacji oraz - tak, przeczytaj dokumentację metody `apply_baseline`).  

Metoda `apply_baseline` działa, jak to mówią programiści *in-place* tzn. zmienia Wam waszą zmienną w pamięci komputera, nie musicie przechwytywać zmienionej kopii. W związku z tym nie musimy tworzyć nowej listy z tfr'ami zbaseline'owanymi - wystarczy jak przejedziemy pętlą przez wszystkie tfr w liście `tfrs` i dla każdego zastosujemy `apply_baseline`.
(baseline robimy taki sam jak na ostatnich zajęciach):

In [ ]:
for tfr in tfrs:
    tfr.____